version: "3"

services:
  node:
    image: node
    container_name: dicio-gauches-api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - dicio-gauches-api-net

  db:
    container_name: dicio-gauches-db
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - dicio-gauches-api-net

networks:
  dicio-gauches-api-net:
    driver: bridge